FROM debian:13-slim

# 1. 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

# 2. 修复可能存在的源连接问题并安装
RUN sed -i 's/deb.debian.org/ftp.us.debian.org/g' /etc/apt/sources.list.d/debian.sources \
    && apt-get update || (sleep 5 && apt-get update) \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    && apt-get install -y --no-install-recommends \
    tzdata \
    openssh-server \
    cron \
    wget \
    curl \
    nano \
    vim \
    iputils-ping \
    net-tools \
    procps \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && mkdir /var/run/sshd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 3. 配置 SSH
RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

# 4. 启动脚本
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 22
VOLUME ["/root", "/opt", "/usr/local/bin"]

ENTRYPOINT ["/entrypoint.sh"]
